CREATE TABLE ORDEM_SERVICO(
	ID int IDENTITY(1,1) NOT NULL,
	CLIENTE_ID BIGINT NOT NULL,
	DESCRICAO TEXT NOT NULL,
	PRECO DECIMAL(10,2) NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	DATA_ABERTURA DATETIME NOT NULL,
	DATA_FINALIZACAO DATETIME,
 CONSTRAINT PK_CLIENTE PRIMARY KEY (ID));

 ALTER TABLE ORDEM_SERVICO ADD CONSTRAINT FK_ORDEM_SERVICO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID);