CREATE TABLE COMENTARIO(
	ID BIGINT NOT NULL IDENTITY,
	ORDEM_SERVICO_ID INT NOT NULL,
	DESCRICAO TEXT NOT NULL,
	DATA_ENVIO DATETIME NOT NULL,

	CONSTRAINT PK_COMENTARIO PRIMARY KEY (ID)
);

ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENTARIO_ORDEM_SERVICO FOREIGN KEY (ORDEM_SERVICO_ID) REFERENCES ORDEM_SERVICO (ID);